### PR TITLE
Add possible values to timer missed_tick_policy parameter documentation

### PR DESCRIPTION
**Pull request by Marenz**

### CODE REVIEW

**Comment by leandro-lucarella-frequenz** [comment]
Can you please remove the `Signed-off-by` in the PR description? I know this is GitHub being silly and not removing it automatically, but otherwise it will be included in the merge commit too.

**Review by leandro-lucarella-frequenz — DISMISSED** [review]

**Comment by leandro-lucarella-frequenz** [comment]
OK, I removed it for you.

**Comment by Marenz** [comment]
Will remove it in future PRs

**Comment by Marenz** [comment]
Rebased, please re-approve

**Review by shsms — DISMISSED** [review]

**Comment by Marenz** [comment]
Oh ffs, clicking the rebase button removes the signature

**Review by leandro-lucarella-frequenz — APPROVED** [review]

**Pull request merged**
