### PR TITLE
Experiment: A syncronous `send()`

### PR DESCRIPTION
**Pull request by mathias-baumann-frequenz**
This little experimental PR makes the `Sender.send()` method syncronous by using
`Event` instead of `Condition` as I saw no need to have an extra lock at that
place.

### CODE REVIEW

**Comment by ela-kotulska-frequenz** [comment]
It is very nice, but it is not enough.
We need blocking Sender anyway: https://github.com/frequenz-floss/frequenz-channels-python/issues/73
So this PR should be extended to make two interfaces, for blocking and non-blocking channels.

**Comment by mathias-baumann-frequenz** [comment]
Adding a send that blocks on queue full shouldn't be a problem

**Comment by mathias-baumann-frequenz** [comment]
But are you sure this should be in this PR? Combining a new feature with changing an existing one?

**Comment by leandro-lucarella-frequenz** [comment]
I created an issue for this: #76

**Comment by leandro-lucarella-frequenz** [comment]
> But are you sure this should be in this PR? Combining a new feature with changing an existing one?

Let's not change the `Sender` now, let's do the proper split in a separate PR, because probably all other channels senders should be sync too.

**Comment by mathias-baumann-frequenz** [comment]
Closing this for now, the branch is still around.

**Pull request closed without merging**
