### PR TITLE
Import the `LatestValueCache` implementation from the Frequenz SDK

### PR DESCRIPTION
**Pull request by shsms**
This PR also adds an integration test for `LatestValueCache`.

### CODE REVIEW

**Review by llucax — COMMENTED** [review]
LGTM, but I would try to keep the user guide documentation up to date too, can you maybe add some high-level documentation with some example to the new private module docstring and expose it via `docs/user-guide/receiving/caching.md` maybe? Similar to [this](https://github.com/frequenz-floss/frequenz-channels-python/blob/v1.x.x/docs/user-guide/receiving/index.md?plain=1).

**Comment by shsms** [comment]
> can you maybe add some high-level documentation with some example

done

**Review by llucax — APPROVED** [review]
Nice, thanks! I think I could make sense to rename `get()` to `value` and make it a `@property`, but this can be discussed separately and done in a separate PR too, so approving anyways.

**Comment by llucax** [comment]
> Nice, thanks! I think I could make sense to rename `get()` to `value` and make it a `@property`, but this can be discussed separately and done in a separate PR too, so approving anyways.

* https://github.com/frequenz-floss/frequenz-channels-python/issues/306

**Pull request merged**
