### PR TITLE
Raise `ChannelClosedError` in Merge if all channels are closed

### PR DESCRIPTION
**Pull request by shsms**

### CODE REVIEW

**Comment by leandro-lucarella-frequenz** [comment]
Sorry I didn't see this before, this is probably covered by #61, which is a big revamp of exceptions.

**Comment by shsms** [comment]
> this is probably covered by https://github.com/frequenz-floss/frequenz-channels-python/pull/61,

no,  because this PR is a condition check,  not the introduction of a new exception type.

**Comment by llucax** [comment]
Yeah, sorry, I meant #62. The commit changing this is the 9ne making `ready()` no-thow. It could be moved to #61 now, at some point it was more intertwined with the select change

**Comment by llucax** [comment]
But if we don't want to merge the commit in #62, there are more places similar to this that we need to fix

**Review by matthias-wende-frequenz — APPROVED** [review]

**Comment by leandro-lucarella-frequenz** [comment]
Now the mentioned commit was moved to #61.

**Pull request closed without merging**
